### ISSUE TITLE
2022-01-26 Meeting

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/CSCN73060-Group6#11]
# Agenda
- [x] #7
- [x] #6 
- [ ] #2 
- [ ] #8
- [x] #10
- [ ] #9

**Comment by ehharvey** [comment]
https://github.com/plasma-umass/coz

**Comment by ehharvey** [comment]
Post-meeting:

# Work Items
- [ ] We are all each working on a workload (see #9). Tentatively, let's aim to have this finished on **Saturday**. We are focusing on measuring the latency for workload items. A simple way of measurement could be to record start and end times of tasks.
- [ ] @Amanuel-Negussie is working on #14, which will be a class that helps manage performance data
- [ ] @ehharvey will look at `coz` #13 , which could help with measurement

**Note:** I just realized that `coz` might make our performance measurement really easy (maybe it can record the data for us). So Emil will look at this soon to see how it operates.

# Other notes
* We want to look into networking libraries #8, but this isn't important for now
* We decided to rewrite the code later. We can't make significant modifications until after week 4, however
* There is an outstanding task in updating the ReadMe, but this isn't important right ow
