### ISSUE TITLE
Investigate networking libraries

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/CSCN73060-Group6#8]
Currently, the project implements networking via `WinSock`, which basically means we are using the OS libraries to handle networking. This works, but it is very low level.

There are a variety of networking libraries available. [This](https://stackoverflow.com/questions/118945/best-c-c-network-library) StackOverflow question has quite a few good suggestions.

# Requirements
* Easy to use
* Easy to integrate with VisualStudio (though if we don't need to use VS, that would be ideal as well :stuck_out_tongue: )
* Cross-platform (Linux + Windows)
* **Maybe make an adapter class to let us use whatever networking library**

## Functions of library
* Multithreading
* (optional) UDP/TCP
* Is low level (ideally the server should receive the raw bytes)

# Todo
- [ ] Find suitable library
- [ ] Discover more functions that might be required/useful for our project
- [x] Document how to integrate with Visual Studio (ideally this should be automated)

**Comment by ehharvey** [comment]
Note: We don't need to code against a specific networking library. We could stub the networking library for now. Later, when we do decide on a library we can write an adapter class to make it work

**Comment by ehharvey** [comment]
I think we are going to settle on Boost. It's mature and popular and says it offers good performance.

**Comment by ehharvey** [comment]
Alternatives (in case Boost fails)
* https://github.com/cpp-netlib/cpp-netlib
* evpp (inactive)
